#!/usr/local/bin/python3
'''
my_name="python"
print(my_name)
print(dir(my_name))
my_name_lower=my_name.lower()
print(my_name_lower)
print(my_name.lower())
print(my_name.upper())
print(my_name.title())
'''
my_name="python"
print(my_name.startswith('p'))
print(my_name.startswith('t'))
print(my_name.endswith('h'))
print(my_name.islower())
print(my_name.istitle())
print(my_name.isspace())

